# Generated by Django 6.0.7 on 2026-07-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.bing.com/images/search?view=detailV2&ccid=2%2bM7NuZ1&id=F35D32AF474DC2998A6601D07E9F74EFDD678072&thid=OIP.2-M7NuZ1n3stCKY5xY3P_gAAAA&mediaurl=https%3a%2f%2fp.kindpng.com%2fpicc%2fs%2f79-798754_hoteles-y-centros-vacacionales-dish-placeholder-hd-png.png&exph=280&expw=280&q=food+item+placeholder&mode=overlay&FORM=IQFRBA&ck=D0905054EEDDFF5E7192268C25DE098E&selectedIndex=0&idpp=serp ', max_length=500),
        ),
    ]
